### ISSUE TITLE
New lsif infexer lsif-dotnet 

### ISSUE THREAD

**Issue by tcz717** [lsif/lsif.github.io#24]
LsifDotnet https://github.com/tcz717/LsifDotnet It is my personal project under Apache license. Through it is initial stage/version, it is enough to be used for real projects. It supports C# only with hover/definition/reference/moniker feature right now. It has docker and GitHub action examples to demonstrate its ability.

I will continue to iterate and improve the project (like adding VB support or nuget moniker)

**Comment by tcz717** [comment]
Any update?

**Comment by varungandhi-src** [comment]
Hey, sorry about this getting lost. I will merge a PR to mention this.
