### ISSUE TITLE
www.lsif.dev gives http 404 error

### ISSUE THREAD

**Issue by vanesa** [lsif/lsif.github.io#5]
When opening [https://lsif.dev](https://lsif.dev) on Chrome, it automatically redirects to https://www.lsif.dev which gives a `404` error:
![image](https://user-images.githubusercontent.com/9110008/66614659-b6fdbe00-eb7e-11e9-9f51-31d1ed1dcfc6.png)

Console Error:
![image](https://user-images.githubusercontent.com/9110008/66615221-a5b5b100-eb80-11e9-95b5-bee313d0a320.png)

[https://lsif.dev](https://lsif.dev) works when you open it in firefox or in an incognito Chrome window, as both don't seem to forward to `www`. Oddly, when opening `www.lsif.dev` in Firefox the page loads, not so in Chrome incognito mode.

I'm not sure if this is related but under settings, Github shows lsif being hosted as `http://lsif.dev` instead of `https`.
![image](https://user-images.githubusercontent.com/9110008/66614781-21166300-eb7f-11e9-8d0d-40dc06e30d05.png)

And we can't enforce `https` because of the following error:
![image](https://user-images.githubusercontent.com/9110008/66614769-18259180-eb7f-11e9-8e42-bf16be680686.png)

Maybe there is domain configuration we are missing?

**Comment by unknwon** [comment]
Did a little experiment.

1. If I visit the site for the first time ever, and type `lsif.dev`, Chrome gives me the correct page. And continue to redirect me to `https://lsif.dev` even if I type `https://www.lsif.dev`.
2. If I for whatever reason, first time typed `www.lsif.dev`, then it remembers and always "help" me to visit `www.lsif.dev` whenever I type `lsif.dev`.

I think it is more likely a Chrome problem not server-side fault...? (unless GitHub configures proxy to behavior unusual)

**Comment by slimsag** [comment]
As far as `Enforce HTTPS` goes, it looks like the A records you have configured are wrong. You have these two in CloudFlare:

```
192.30.252.153
192.30.252.154
```

But [GitHub's docs](https://help.github.com/en/articles/managing-a-custom-domain-for-your-github-pages-site) suggest these four:

```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

Once you configure those and it propagates, the enforce HTTPS option should work.

**Comment by vanesa** [comment]
Ok, it's fixed. An extra A record was setup for this domain that wasn’t referenced in terraform, that's what was causing the issue! We deleted the third record and now it works. 
![image](https://user-images.githubusercontent.com/9110008/66786744-59c37e80-ee96-11e9-856d-cd1a9f1ed90a.png)
